#!/bin/bash
set -e

echo "Running additional setup for MQTT Manager (mqtt2) plugin..."
# Local Mosquitto broker, installed by mqtt2 ("local" mode) with apt.
# Configuration and certificates are still generated by the plugin.
# Note: mqtt2 "docker" mode refuses to run when a local broker is installed.
apt-get install --no-install-recommends -y mosquitto
